//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA_Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<DEL_TBADMINISMOVIMIE> DEL_TBADMINISMOVIMIE { get; set; }
        public DbSet<TBBANDERA> TBBANDERAs { get; set; }
        public DbSet<TBBITACORERRORE> TBBITACORERRORES { get; set; }
        public DbSet<TBCLIENTE> TBCLIENTEs { get; set; }
        public DbSet<TBCOBASI> TBCOBASIs { get; set; }
        public DbSet<TBCOBERTUNOTA> TBCOBERTUNOTAS { get; set; }
        public DbSet<TBCOMPANI> TBCOMPANIs { get; set; }
        public DbSet<TBCORREDOR> TBCORREDORs { get; set; }
        public DbSet<TBCOTIZACION> TBCOTIZACIONs { get; set; }
        public DbSet<TBEJECUTI> TBEJECUTIs { get; set; }
        public DbSet<TBERROR> TBERRORs { get; set; }
        public DbSet<TBGRUPRAMO> TBGRUPRAMOes { get; set; }
        public DbSet<TBMONEDA> TBMONEDAs { get; set; }
        public DbSet<TBOPORCOTIRAMO> TBOPORCOTIRAMOes { get; set; }
        public DbSet<TBOPORCREACOTI> TBOPORCREACOTIs { get; set; }
        public DbSet<TBRAMO> TBRAMOes { get; set; }
        public DbSet<TBROL> TBROLs { get; set; }
        public DbSet<TBSUCURSA> TBSUCURSAs { get; set; }
        public DbSet<TBTIPOOCUP> TBTIPOOCUPs { get; set; }
        public DbSet<DEL_TBEXCEPCIONES> DEL_TBEXCEPCIONES { get; set; }
        public DbSet<DEL_TBRESPUESTAAPI> DEL_TBRESPUESTAAPI { get; set; }
        public DbSet<TBCOTIZACIONUBIC> TBCOTIZACIONUBICs { get; set; }
        public DbSet<TBCOTRAMMAT> TBCOTRAMMATs { get; set; }
        public DbSet<TBCOTRAMNOT> TBCOTRAMNOTs { get; set; }
        public DbSet<TBCUESUBIC> TBCUESUBICs { get; set; }
        public DbSet<TBEXCELIBERESE> TBEXCELIBERESEs { get; set; }
        public DbSet<TBFORMAPAGO> TBFORMAPAGOes { get; set; }
        public DbSet<TBHOMOCAMPPIPECOTIRESE> TBHOMOCAMPPIPECOTIRESEs { get; set; }
        public DbSet<TBHOMOCAMPVALOPIPE> TBHOMOCAMPVALOPIPEs { get; set; }
        public DbSet<TBITEM> TBITEMS { get; set; }
        public DbSet<TBMONASEBA> TBMONASEBAS { get; set; }
        public DbSet<TBOCUPACI> TBOCUPACIs { get; set; }
        public DbSet<TBOPORTUNIDAD> TBOPORTUNIDADs { get; set; }
        public DbSet<TBOPORTUNRECIENT> TBOPORTUNRECIENTs { get; set; }
        public DbSet<TBPLANPAGO> TBPLANPAGOes { get; set; }
        public DbSet<TBPRECUERAM> TBPRECUERAMs { get; set; }
        public DbSet<TBRESERVA> TBRESERVAs { get; set; }
        public DbSet<TBTIPORy> TBTIPORIES { get; set; }
        public DbSet<TBUBICACION> TBUBICACIONs { get; set; }
        public DbSet<DEL_TBCOTIZACIONRAMO> DEL_TBCOTIZACIONRAMO { get; set; }
        public DbSet<TBCOMUNA> TBCOMUNAs { get; set; }
        public DbSet<TBREGION> TBREGIONs { get; set; }
        public DbSet<TBTOOLTIP> TBTOOLTIPs { get; set; }
        public DbSet<TBBANDEJAENTRADA> TBBandejaEntrada { get; set; }
    }
}
