//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEL_TBEXCEPCIONES
    {
        public long IDEXC { get; set; }
        public long IDTIPMOV { get; set; }
        public string CODTIPERR { get; set; }
        public string MEN { get; set; }
        public string JSO { get; set; }
        public Nullable<System.DateTime> FECAUD { get; set; }
        public string REP { get; set; }
    }
}
