//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEL_TBCOTIZACIONRAMO
    {
        public long IDCOTRAM { get; set; }
        public long IDCOT { get; set; }
        public long IDRAM { get; set; }
        public string ACT { get; set; }
    }
}
