//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEL_TBRESPUESTAAPI
    {
        public long IDRESAPI { get; set; }
        public long IDTIPMOV { get; set; }
        public string RESCOD { get; set; }
        public string VOUNUM { get; set; }
        public string VIN { get; set; }
        public string GLOJSO { get; set; }
        public string GLOJSOSAL { get; set; }
        public string GLOJSOENT { get; set; }
        public string CODDOC { get; set; }
        public System.DateTime FECAUD { get; set; }
        public string RESMES { get; set; }
    }
}
