//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBBANDERA
    {
        public TBBANDERA()
        {
            this.TBCOTIZACIONs = new HashSet<TBCOTIZACION>();
        }
    
        public long IDBAN { get; set; }
        public string NOMBAN { get; set; }
    
        public virtual ICollection<TBCOTIZACION> TBCOTIZACIONs { get; set; }
    }
}
