//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Runtime.Serialization;

namespace DA_Model
{
    public class TBBANDEJAENTRADA
    {
        [DataMember(Name = "Id Cotizacion")]
        public Int64 IDCOT { get; set; }

        [DataMember(Name = "Rut Corredor Pipedrive")]
        public string RUTCORPIP { get; set; }

        [DataMember(Name = "Nombre Razon Social")]
        public string NOMRAZSOCCOT { get; set; }

        [DataMember(Name = "Codigo Sucursal")]
        public string CODSUC { get; set; }

        [DataMember(Name = "Descripcion Sucursal")]
        public string DESSUC { get; set; }

        [DataMember(Name = "Rut Cliente Pipedrive")]
        public string RUTCLIPIP { get; set; }

        [DataMember(Name = "Razon Social Cliente")]
        public string RAZSOCCLI { get; set; }

        [DataMember(Name = "Fecha Creacion Cotizacion")]
        public DateTime? FECCRECOT { get; set; }

        [DataMember(Name = "Descripcion Oportunidad Cotizacion")]
        public string DESOPOCOT { get; set; }

        [DataMember(Name = "Nombre Ejecutivo Comercial")]
        public string NOMEJECOMCOT { get; set; }

        [DataMember(Name = "Id Suscriptor")]
        public decimal? IDSUSCRIP { get; set; }
    }
}