//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBBITACORERRORE
    {
        public long IDBITACORERRORES { get; set; }
        public Nullable<System.DateTime> FECHAPETICIO { get; set; }
        public Nullable<System.DateTime> FECHARESPUES { get; set; }
        public string SISTEMA { get; set; }
        public string ACCION { get; set; }
        public string GRAVEDA { get; set; }
        public string MODULOS { get; set; }
        public string CAMPO { get; set; }
        public long IDERROR { get; set; }
    
        public virtual TBERROR TBERROR { get; set; }
    }
}
