//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBCLIENTE
    {
        public string RUTCLI { get; set; }
        public string NOMCLI { get; set; }
        public string EMACLI { get; set; }
        public string DIRCLI { get; set; }
        public string TELCLI { get; set; }
    }
}
