//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBCOTIZACIONUBIC
    {
        public long IDCOTUBI { get; set; }
        public long IDCOT { get; set; }
        public string DIRECCI { get; set; }
        public Nullable<long> DIRNRO { get; set; }
        public Nullable<long> IDREG { get; set; }
        public Nullable<long> IDCOMU { get; set; }
        public Nullable<long> IDMURO { get; set; }
        public Nullable<long> IDTECHO { get; set; }
        public Nullable<long> ANOCONSTRU { get; set; }
    }
}
