//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBCOBASI
    {
        public TBCOBASI()
        {
            this.TBCOBERTUNOTAS = new HashSet<TBCOBERTUNOTA>();
        }
    
        public long IDCOBASI { get; set; }
        public long IDUBI { get; set; }
        public long MONASE { get; set; }
        public long PRIAFE { get; set; }
        public long PRIEXC { get; set; }
        public long COM { get; set; }
        public string LIM { get; set; }
        public string SUBLIM { get; set; }
        public string DED { get; set; }
        public long PRINET { get; set; }
    
        public virtual ICollection<TBCOBERTUNOTA> TBCOBERTUNOTAS { get; set; }
    }
}
