//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBCOTIZACION
    {
        public long IDCOT { get; set; }
        public long IDOPOCRECOT { get; set; }
        public Nullable<long> IDRES { get; set; }
        public Nullable<long> IDRAM { get; set; }
        public Nullable<long> IDBAN { get; set; }
        public Nullable<long> IDEJECOM { get; set; }
        public string CODSUC { get; set; }
        public string ACTIVID { get; set; }
        public Nullable<decimal> CODMON { get; set; }
        public Nullable<decimal> CODCOM { get; set; }
        public Nullable<System.DateTime> FECPRESENT { get; set; }
        public Nullable<System.DateTime> FECEPCPOL { get; set; }
        public Nullable<decimal> LICITAC { get; set; }
        public Nullable<decimal> IDSUSCRIP { get; set; }
    
        public virtual TBBANDERA TBBANDERA { get; set; }
        public virtual TBSUCURSA TBSUCURSA { get; set; }
        public virtual TBOPORCREACOTI TBOPORCREACOTI { get; set; }
        public virtual TBEJECUTI TBEJECUTI { get; set; }
    }
}
