//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBEXCELIBERESE
    {
        public long IDEXCLIBRES { get; set; }
        public string RUTCOR { get; set; }
        public string RUTCLI { get; set; }
        public long IDGRURAM { get; set; }
        public Nullable<System.DateTime> FECINI { get; set; }
        public Nullable<System.DateTime> FECFIN { get; set; }
    }
}
