//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBHOMOCAMPPIPECOTIRESE
    {
        public long IDHOM { get; set; }
        public Nullable<long> IDPIP { get; set; }
        public string KEYPIP { get; set; }
        public string NAMPIP { get; set; }
        public string AMB { get; set; }
        public string TIPUSO { get; set; }
        public string NOMCAMCOT { get; set; }
    }
}
