//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBOCUPACI
    {
        public long IDOCUPACI { get; set; }
        public long IDRAMO { get; set; }
        public long IDTIPORIESGO { get; set; }
        public long IDTIPOOCUPACI { get; set; }
        public string ACTIVID { get; set; }
    }
}
