//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBOPORCREACOTI
    {
        public TBOPORCREACOTI()
        {
            this.TBCOTIZACIONs = new HashSet<TBCOTIZACION>();
            this.TBOPORCOTIRAMOes = new HashSet<TBOPORCOTIRAMO>();
        }
    
        public long IDOPOCRECOT { get; set; }
        public Nullable<long> IDDEAPIP { get; set; }
        public string RUTCLIPIP { get; set; }
        public string RAZSOCCLI { get; set; }
        public string RUTCORPIP { get; set; }
        public string NOMRAZSOCCOT { get; set; }
        public string APECOR { get; set; }
        public string RUTEJECOMCOT { get; set; }
        public string NOMEJECOMCOT { get; set; }
        public string APEEJECOMCOT { get; set; }
        public string EMAEJECOMCOT { get; set; }
        public string SUCCOT { get; set; }
        public Nullable<long> GRURAMCOT { get; set; }
        public string DESOPOCOT { get; set; }
        public Nullable<System.DateTime> FECCRECOT { get; set; }
        public string ESTOPOPIP { get; set; }
        public Nullable<long> IDSTAPIP { get; set; }
        public string NOMCONCOR { get; set; }
        public string EMAILCLI { get; set; }
        public string TELCLI { get; set; }
    
        public virtual ICollection<TBCOTIZACION> TBCOTIZACIONs { get; set; }
        public virtual ICollection<TBOPORCOTIRAMO> TBOPORCOTIRAMOes { get; set; }
    }
}
