//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBSUCURSA
    {
        public TBSUCURSA()
        {
            this.TBCOTIZACIONs = new HashSet<TBCOTIZACION>();
        }
    
        public string CODSUC { get; set; }
        public string DESSUC { get; set; }
        public string CODPIP { get; set; }
    
        public virtual ICollection<TBCOTIZACION> TBCOTIZACIONs { get; set; }
    }
}
